### ISSUE TITLE
single video spider

### ISSUE THREAD

**Issue by flozxwer** [AkagawaTsurunaki/BiliChatSpider#1]
Could you please add a new function that helps to collect comments under a single video? It would be pretty good for your program.

**Comment by AkagawaTsurunaki** [comment]
Thanks for your suggestion. @flozxwer 

I have added this function in the latest version **BiliChatSpider ver1.1** after I fixed some bugs. You can specified the uid of an UP, and then collect comments within a specified video list. 

For more details, just read the updated README.md.
