### ISSUE TITLE
Collecting multi-round conversations

### ISSUE THREAD

**Issue by Vertineko** [AkagawaTsurunaki/BiliChatSpider#2]
I need the function of collecting multi-round conversations data from bilibili, could the author update this function? @AkagawaTsurunaki

**Comment by AkagawaTsurunaki** [comment]
Thank you very much for your suggestion.
Since I don't have enough free time, I can't update it immediately. But you can use `ReplyNode` in the `xhs` branch to build on the function you want. @Vertineko

**Comment by PermissionDog** [comment]
I can complete this task, please assign it to me. @AkagawaTsurunaki

**Comment by AkagawaTsurunaki** [comment]
> I can complete this task, please assign it to me. @AkagawaTsurunaki

Thank you! @PermissionDog 
You are assignee now!

**Comment by AkagawaTsurunaki** [comment]
Thank you! @PermissionDog 
The function has been added in module `xiaohongshu`, and will be added in `Bilibili` in the near future.
