### ISSUE TITLE
Improper warning when running xhs.py

### ISSUE THREAD

**Issue by AkagawaTsurunaki** [AkagawaTsurunaki/BiliChatSpider#8]
When I try to run `xhs.py` , I found warning
`'❓️ "{save_path}" does not exist, shall we create it for you? [y]/N'`.
But I don't need this tip when I just wanna run `xhs.py`.
Could anyone help me?

**Comment by NeuSoftKK** [comment]
Hi developer, I thought I could help with this issue, it could be due to the logic of the subroutine call, I would try to abstract the same code into a subfunction

**Comment by AkagawaTsurunaki** [comment]
> Hi developer, I thought I could help with this issue, it could be due to the logic of the subroutine call, I would try to abstract the same code into a subfunction

Thank you! You are assignee now! @NeuSoftKK

**Comment by AkagawaTsurunaki** [comment]
Thank you for your help! @NeuSoftKK
